[package]
name = "rustchat-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chat_security = {path="../chat_security/"}
clap = { version = "4.5.37", features = ["derive"] }
tokio = { version = "1", features = ["rt", "net", "macros", "rt-multi-thread", "sync", ] }
