[package]
name = "chat_security"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
x25519-dalek = "2"
serde = {version = "1.0", features = ["derive"]}
bincode = "1.3"
hkdf = "0.12"
sha2 = "0.10"
chacha20poly1305 = { version = "0.10"}